const titles = ["Обработка естественного языка","Место NLP в дисциплине","Что должен доказать эксперимент","Финансовая новость как структурированный сигнал","Обзор литературы и гипотеза","От символа к вектору","BPE и SentencePiece","Статические и контекстные представления","RNN, LSTM и GRU","Self-attention","Multi-head attention","Encoder, decoder и маски","BERT","RuBERT","FinBERT","XLM-R","DeBERTa-v3","GPT","Llama 3.1","Mistral 7B","Qwen2.5-7B","GigaChat Family","Выбор архитектуры","Fine-tuning, LoRA и prompting","Структурированный вывод","NER","Macro-F1","Паспорт данных","Temporal split","Метрики","Калибровка confidence","Правило выбора","Демонстрация NLP","Сравнение моделей","Схема эксперимента","Результаты Macro-F1","Анализ ошибок","Выводы по гипотезам","Контракт для CV","Требования к отчету","Источники","Маршрут выполнения","Подключение моделей","BERT: извлечённая суммаризация","OpenAI Responses API","Llama: локальная генерация","Mistral API","Qwen: локальная генерация","GigaChat API","Financial PhraseBank","Загрузка из Kaggle","Пример записи и контроль качества"];
let current = 1;
const image = document.querySelector('#slideImage'), number = document.querySelector('#currentSlide'), title = document.querySelector('#slideTitle'), range = document.querySelector('#slideRange');
function showSlide(value){current=Math.max(1,Math.min(52,Number(value)));image.src=`assets/slides/nlp/slide-${current}.webp`;image.alt=`Слайд ${current}: ${titles[current-1]}`;number.textContent=current;title.textContent=titles[current-1];range.value=current;history.replaceState(null,'',`#slide-${current}`)}
document.querySelectorAll('#nextSlide,#nextButton').forEach(b=>b.addEventListener('click',()=>showSlide(current+1)));
document.querySelectorAll('#prevSlide,#prevButton').forEach(b=>b.addEventListener('click',()=>showSlide(current-1)));
range.addEventListener('input',e=>showSlide(e.target.value));
document.querySelector('#fullScreen').addEventListener('click',()=>document.querySelector('.slide-stage').requestFullscreen?.());
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')showSlide(current+1);if(e.key==='ArrowLeft')showSlide(current-1);if(e.key==='Home')showSlide(1);if(e.key==='End')showSlide(52)});
const initial=location.hash.match(/slide-(\d+)/); showSlide(initial?initial[1]:1);
