const configs={
  cv:{name:'Презентация CV',lab:'Лабораторная работа 2',count:29,folder:'cv',back:'lab2-cv.html',pptx:'materials/ПЗМО_Лабораторная_2_CV_теория_модели_демонстрация.pptx',titles:['Компьютерное зрение','Цель и исследовательская логика','Связь лабораторных','Основные задачи CV','Тензор и нормализация','Свёртка','ResNet','EfficientNet','Vision Transformer','Swin Transformer','YOLO','DETR','U-Net','SAM 2','CLIP','DINOv2','OCR и fusion','Подключение CV-моделей','YOLO: код','SAM 2: код','CLIP: код','DINOv2: код','Данные','Утечки','Метрики','Демонстрация','Результаты','Выводы','Источники']},
  recsys:{name:'Презентация Recsys',lab:'Лабораторная работа 3',count:29,folder:'recsys',back:'lab3-recsys.html',pptx:'materials/ПЗМО_Лабораторная_3_Рекомендательные_системы.pptx',titles:['Рекомендательные системы','Цель','Implicit feedback','Схема событий','Temporal split','Candidate set','Popularity и ItemKNN','Implicit ALS','BPR','NCF','LightGCN','SASRec','BERT4Rec','Two-tower','Мультимодальный tower','Ограничения','NDCG@K','Beyond-accuracy','Cold start','Подключение библиотек','implicit ALS: код','RecBole: код','TFRS: код','Демонстрация','Результаты','Абляции','Анализ ошибок','Контракт','Источники']},
  project:{name:'Презентация проекта',lab:'Лабораторная работа 4',count:27,folder:'project',back:'lab4-project.html',pptx:'materials/ПЗМО_Лабораторная_4_Итоговый_проект.pptx',titles:['Итоговый ML-проект','Цель','Критерии приемки','Архитектура','Контракты','Lineage','Замороженный test','Baseline','Абляции','Неопределенность','Системные метрики','SLA','Fallback','Risk register','Human-in-the-loop','Datasheet','Model card','MLflow','DVC','FastAPI','Мониторинг','Docker Compose','Демонстрация','Результаты','Защита','Вывод','Источники']}
};
const key=new URLSearchParams(location.search).get('deck')||'cv',cfg=configs[key]||configs.cv;let current=1;
document.title=`${cfg.name} — ПЗМО`;document.querySelector('#deckName').textContent=cfg.name;document.querySelector('#labName').textContent=cfg.lab;document.querySelector('#backBrand').href=cfg.back;document.querySelector('#backLink').href=cfg.back;document.querySelector('#downloadLink').href=cfg.pptx;document.querySelector('#slideCountLabel').textContent=`${cfg.count} слайдов`;document.querySelector('#totalSlides').textContent=`/ ${cfg.count}`;document.querySelector('#slideRange').max=cfg.count;
const image=document.querySelector('#slideImage'),number=document.querySelector('#currentSlide'),title=document.querySelector('#slideTitle'),range=document.querySelector('#slideRange');
function showSlide(value){current=Math.max(1,Math.min(cfg.count,Number(value)));const label=cfg.titles[current-1]||`Слайд ${current}`;image.src=`assets/slides/${cfg.folder}/slide-${current}.webp`;image.alt=`Слайд ${current}: ${label}`;number.textContent=current;title.textContent=label;range.value=current;history.replaceState(null,'',`${location.pathname}?deck=${key}#slide-${current}`)}
document.querySelectorAll('#nextSlide,#nextButton').forEach(b=>b.addEventListener('click',()=>showSlide(current+1)));document.querySelectorAll('#prevSlide,#prevButton').forEach(b=>b.addEventListener('click',()=>showSlide(current-1)));range.addEventListener('input',e=>showSlide(e.target.value));document.querySelector('#fullScreen').addEventListener('click',()=>document.querySelector('.slide-stage').requestFullscreen?.());document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')showSlide(current+1);if(e.key==='ArrowLeft')showSlide(current-1);if(e.key==='Home')showSlide(1);if(e.key==='End')showSlide(cfg.count)});const initial=location.hash.match(/slide-(\d+)/);showSlide(initial?initial[1]:1);
